image: edbizarro/gitlab-ci-pipeline-php:7.3-alpine

# Setup common stages
stages:
  - build
  - test

cache:
  key: "${CI_COMMIT_REF_SLUG}"
  paths:
    - vendor/
    - .composer-cache/
    - phpcpd.phar
    - .phpunit.result.cache

# Start by creating the vendor folder for the stages
composer:
  stage: build
  artifacts:
    expire_in: 1 day
    paths:
      - vendor/
  script:
    - composer config -g cache-dir "$(pwd)/.composer-cache"
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts -o

# Check Code Style
codestyle:
  stage: test
  image: lorisleiva/laravel-docker
  environment:
    name: testing
  artifacts:
    paths:
      - reports
      - ./storage/logs
    expire_in: 1 day
    when: on_failure
  before_script:
    - mkdir -p ./reports
  script:
    - phpcs --standard=PSR2 --extensions=php --report=full --report-file=./reports/$CI_COMMIT_SHA.txt -v src

# Check for any copy-paste code in the codebase
phpcpd:
  stage: test
  environment:
    name: testing
  before_script:
    - test -f phpcpd.phar || curl -L https://phar.phpunit.de/phpcpd.phar -o phpcpd.phar
  script:
    - php phpcpd.phar app/ --min-lines=50

# Security check on the whole dependencies tree
sensiolabs:
  stage: test
  environment:
    name: testing
  artifacts:
    paths:
      - reports
    expire_in: 1 days
    when: on_failure
  before_script:
    - mkdir -p ./reports
    - test -d security-checker || git clone https://github.com/sensiolabs/security-checker.git
    - cd security-checker
    - composer install
  script:
    - php security-checker security:check ../composer.lock

# Testing time
unit:
  stage: test
  environment:
    name: testing
  needs: ["composer"]
  dependencies:
    - composer
  artifacts:
    paths:
      - reports
    expire_in: 1 day
    when: on_failure
  before_script:
    - mkdir -p ./reports
  script:
    - ./vendor/bin/phpunit --colors=never
