version: "3.7"
services:
  workspace:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-eloquent-traits
    container_name: let_workspace
    restart: on-failure
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    tty: true